#!/usr/bin/env bash

# Insert the main script and its dependencies into the
# SVG file. This is the only way we can actually run our
# code in modern browsers WITHOUT relying on a local server
# because of same-origin nonsense.

# Thanks Copilot
sed -z -E -i \
  "s|(<svg[^>]*>)|\\1\n\
\t<script href=\"./utils.js\"></script>\n\
\t<script href=\"./bracket-hole-carving.js\"></script>\n\
\t<script href=\"./lang-sweettalk.js\"></script>\n\
\t<script href=\"./lang-descartes.js\"></script>\n\
\t<script href=\"./main-engine.js\"></script>\n\
\t<script href=\"./omnimeta.js\"></script>|" \
 $1
