#!/usr/bin/env perl
# Originally generated by Claude Opus 4.5. Currently 4.8
# Invoke as follows:
# perl jstalk2js.pl < jstalk-test.jstalk.js > jstalk-test.js
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

# Transpile Smalltalk-style message syntax to JS send() calls
# ⟦obj myMessage: arg1 with: arg2 and: arg3⟧
# becomes: send(obj, 'myMessage:', arg1, 'with:', arg2, 'and:', arg3)
# And ⟦super myMessage: arg1 with: arg2 and: arg3⟧
# becomes: supr('myMessage:', arg1, 'with:', arg2, 'and:', arg3)

my $OPEN = '⟦';
my $CLOSE = '⟧';

sub find_matching_bracket {
    my ($str, $start) = @_;
    my $depth = 1;
    my $pos = $start;
    my $len = length($str);
    
    while ($pos < $len && $depth > 0) {
        my $ch = substr($str, $pos, 1);
        if ($ch eq $OPEN) {
            $depth++;
        } elsif ($ch eq $CLOSE) {
            $depth--;
        }
        $pos++ if $depth > 0;
    }
    return $depth == 0 ? $pos : -1;
}

sub find_matching {
    my ($str, $start, $open, $close) = @_;
    my $depth = 1;
    my $pos = $start;
    my $len = length($str);
    
    while ($pos < $len && $depth > 0) {
        my $ch = substr($str, $pos, 1);
        if ($ch eq $open) {
            $depth++;
        } elsif ($ch eq $close) {
            $depth--;
        }
        $pos++ if $depth > 0;
    }
    return $depth == 0 ? $pos : -1;
}

# Array-based matching-⟦⟧ finder for the outer scan. Indexes a shared character
# array in O(1) (no substr on a multibyte string), scanning within [$start,$hi).
# Returns the index of the matching CLOSE, or -1 if unbalanced.
sub find_matching_bracket_arr {
    my ($chars, $start, $hi) = @_;
    my $depth = 1;
    my $pos = $start;
    while ($pos < $hi && $depth > 0) {
        my $ch = $chars->[$pos];
        if ($ch eq $OPEN) {
            $depth++;
        } elsif ($ch eq $CLOSE) {
            $depth--;
        }
        $pos++ if $depth > 0;
    }
    return $depth == 0 ? $pos : -1;
}

sub skip_balanced {
    my ($str, $pos) = @_;
    my $len = length($str);
    my $ch = substr($str, $pos, 1);
    
    if ($ch eq $OPEN) {
        return find_matching_bracket($str, $pos + 1);
    } elsif ($ch eq '[') {
        return find_matching($str, $pos + 1, '[', ']');
    } elsif ($ch eq '(') {
        return find_matching($str, $pos + 1, '(', ')');
    } elsif ($ch eq '{') {
        return find_matching($str, $pos + 1, '{', '}');
    } elsif ($ch eq '"' || $ch eq "'" || $ch eq '`') {
        my $quote = $ch;
        $pos++;
        while ($pos < $len) {
            my $c = substr($str, $pos, 1);
            if ($c eq '\\') {
                $pos += 2;
            } elsif ($c eq $quote) {
                return $pos;
            } else {
                $pos++;
            }
        }
        return $pos - 1;
    }
    return $pos;
}

sub has_top_level_comma {
    my ($str) = @_;
    my $pos = 0;
    my $len = length($str);
    
    while ($pos < $len) {
        my $ch = substr($str, $pos, 1);
        if ($ch eq ',') {
            return 1;
        } elsif ($ch eq $OPEN || $ch eq '[' || $ch eq '(' || $ch eq '{' || $ch eq '"' || $ch eq "'" || $ch eq '`') {
            $pos = skip_balanced($str, $pos) + 1;
        } else {
            $pos++;
        }
    }
    return 0;
}

# Tokenize preserving whitespace info
# Returns array of [token, preceding_whitespace] pairs
sub tokenize_message {
    my ($content) = @_;
    
    my @result;
    my $pos = 0;
    my $len = length($content);
    my $current = '';
    my $preceding_ws = '';
    
    # Capture leading whitespace
    while ($pos < $len && substr($content, $pos, 1) =~ /\s/) {
        $preceding_ws .= substr($content, $pos, 1);
        $pos++;
    }
    
    while ($pos < $len) {
        my $ch = substr($content, $pos, 1);
        
        if ($ch eq $OPEN || $ch eq '[' || $ch eq '(' || $ch eq '{' || $ch eq '"' || $ch eq "'" || $ch eq '`') {
            my $end = skip_balanced($content, $pos);
            $current .= substr($content, $pos, $end - $pos + 1);
            $pos = $end + 1;
        } elsif ($ch =~ /\s/) {
            if ($current ne '') {
                push @result, [$current, $preceding_ws];
                $current = '';
                $preceding_ws = '';
            }
            $preceding_ws .= $ch;
            $pos++;
        } elsif ($ch eq ':') {
            if ($current ne '' && $current =~ /^[a-zA-Z_][a-zA-Z0-9_]*$/) {
                $current .= ':';
                push @result, [$current, $preceding_ws];
                $current = '';
                $preceding_ws = '';
            } else {
                $current .= ':';
            }
            $pos++;
        } else {
            $current .= $ch;
            $pos++;
        }
    }
    push @result, [$current, $preceding_ws] if $current ne '';
    
    return @result;
}

sub parse_message_send {
    my ($content) = @_;
    
    return undef if has_top_level_comma($content);
    
    my @tokens = tokenize_message($content);
    
    return undef if @tokens == 0;
    
    my ($receiver, $recv_ws) = @{shift @tokens};
    
    return undef if @tokens == 0;
    
    # Unary message
    if (@tokens == 1 && $tokens[0][0] =~ /^[a-zA-Z_][a-zA-Z0-9_]*$/) {
        my ($sel, $sel_ws) = @{$tokens[0]};
        return [
            [$receiver, ''],
            ["'$sel'", $sel_ws]
        ];
    }
    
    return undef unless $tokens[0][0] =~ /^[a-zA-Z_][a-zA-Z0-9_]*:$/;
    
    my @parts = ([$receiver, '']);
    
    while (@tokens) {
        my ($tok, $ws) = @{shift @tokens};
        
        if ($tok =~ /^[a-zA-Z_][a-zA-Z0-9_]*:$/) {
            push @parts, ["'$tok'", $ws];
            if (@tokens) {
                my ($arg, $arg_ws) = @{shift @tokens};
                push @parts, [$arg, $arg_ws];
            }
        } else {
            if (@parts > 0) {
                $parts[-1][0] .= ' ' . $tok;
            }
        }
    }
    
    return \@parts;
}

sub format_send {
    my ($parts) = @_;
    
    # Special receiver: `super` transpiles to supr(...) with the receiver dropped,
    # since `super` is a reserved word in JS.
    my $func = 'send';
    my @items = @$parts;
    if (@items && $items[0][0] eq 'super') {
        $func = 'supr';
        shift @items;   # drop the `super` receiver; supr() takes only selector/arg pairs
    }
    
    # Emit func(...), preserving original whitespace where it contains newlines
    # (so multiline message sends keep their formatting) and using ", " otherwise.
    # The leading item emits its own whitespace only if it contains a newline, which
    # only happens in the super case (a normal receiver has empty leading whitespace).
    my $out = $func . '(';
    for my $i (0 .. $#items) {
        my ($tok, $ws) = @{$items[$i]};
        if ($i == 0) {
            $out .= $ws if $ws =~ /\n/;
        } else {
            $out .= ',';
            $out .= ($ws =~ /\n/) ? $ws : ' ';
        }
        $out .= $tok;
    }
    $out .= ')';
    return $out;
}

# Outer transpile pass. Operates on a shared character array over the half-open
# index range [$lo, $hi), so all character access is O(1) — this is what removes
# the previous O(n^2) behaviour on large inputs. Returns the transpiled string.
sub transpile_range {
    my ($chars, $lo, $hi) = @_;
    my $output = '';
    my $pos = $lo;
    
    while ($pos < $hi) {
        my $ch = $chars->[$pos];
        
        if ($ch eq $OPEN) {
            my $end = find_matching_bracket_arr($chars, $pos + 1, $hi);
            if ($end == -1) {
                $output .= $ch;
                $pos++;
            } else {
                # Content occupies indices [$pos+1, $end); recurse to convert any
                # nested ⟦⟧, then parse the resulting (short) string as a send.
                my $transpiled = transpile_range($chars, $pos + 1, $end);
                my $parts = parse_message_send($transpiled);
                if (defined $parts) {
                    $output .= format_send($parts);
                } else {
                    $output .= $OPEN . $transpiled . $CLOSE;
                }
                $pos = $end + 1;
            }
        } else {
            $output .= $ch;
            $pos++;
        }
    }
    
    return $output;
}

my $input = do { local $/; <STDIN> };
my @chars = split //, $input;
print transpile_range(\@chars, 0, scalar @chars);