#!/usr/bin/env perl
# Generated by Claude Opus 4.5.
# Invoke as follows:
# perl jstalk2js.pl < jstalk-test.jstalk.js > jstalk-test.js
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

# Transpile Smalltalk-style message syntax to JS send() calls
# ⟦obj myMessage: arg1 with: arg2 and: arg3⟧
# becomes: send(obj, 'myMessage:', arg1, 'with:', arg2, 'and:', arg3)

my $OPEN = '⟦';
my $CLOSE = '⟧';

sub find_matching_bracket {
    my ($str, $start) = @_;
    my $depth = 1;
    my $pos = $start;
    my $len = length($str);
    
    while ($pos < $len && $depth > 0) {
        my $ch = substr($str, $pos, 1);
        if ($ch eq $OPEN) {
            $depth++;
        } elsif ($ch eq $CLOSE) {
            $depth--;
        }
        $pos++ if $depth > 0;
    }
    return $depth == 0 ? $pos : -1;
}

sub find_matching {
    my ($str, $start, $open, $close) = @_;
    my $depth = 1;
    my $pos = $start;
    my $len = length($str);
    
    while ($pos < $len && $depth > 0) {
        my $ch = substr($str, $pos, 1);
        if ($ch eq $open) {
            $depth++;
        } elsif ($ch eq $close) {
            $depth--;
        }
        $pos++ if $depth > 0;
    }
    return $depth == 0 ? $pos : -1;
}

sub skip_balanced {
    my ($str, $pos) = @_;
    my $len = length($str);
    my $ch = substr($str, $pos, 1);
    
    if ($ch eq $OPEN) {
        return find_matching_bracket($str, $pos + 1);
    } elsif ($ch eq '[') {
        return find_matching($str, $pos + 1, '[', ']');
    } elsif ($ch eq '(') {
        return find_matching($str, $pos + 1, '(', ')');
    } elsif ($ch eq '{') {
        return find_matching($str, $pos + 1, '{', '}');
    } elsif ($ch eq '"' || $ch eq "'" || $ch eq '`') {
        my $quote = $ch;
        $pos++;
        while ($pos < $len) {
            my $c = substr($str, $pos, 1);
            if ($c eq '\\') {
                $pos += 2;
            } elsif ($c eq $quote) {
                return $pos;
            } else {
                $pos++;
            }
        }
        return $pos - 1;
    }
    return $pos;
}

sub has_top_level_comma {
    my ($str) = @_;
    my $pos = 0;
    my $len = length($str);
    
    while ($pos < $len) {
        my $ch = substr($str, $pos, 1);
        if ($ch eq ',') {
            return 1;
        } elsif ($ch eq $OPEN || $ch eq '[' || $ch eq '(' || $ch eq '{' || $ch eq '"' || $ch eq "'" || $ch eq '`') {
            $pos = skip_balanced($str, $pos) + 1;
        } else {
            $pos++;
        }
    }
    return 0;
}

# Tokenize preserving whitespace info
# Returns array of [token, preceding_whitespace] pairs
sub tokenize_message {
    my ($content) = @_;
    
    my @result;
    my $pos = 0;
    my $len = length($content);
    my $current = '';
    my $preceding_ws = '';
    
    # Capture leading whitespace
    while ($pos < $len && substr($content, $pos, 1) =~ /\s/) {
        $preceding_ws .= substr($content, $pos, 1);
        $pos++;
    }
    
    while ($pos < $len) {
        my $ch = substr($content, $pos, 1);
        
        if ($ch eq $OPEN || $ch eq '[' || $ch eq '(' || $ch eq '{' || $ch eq '"' || $ch eq "'" || $ch eq '`') {
            my $end = skip_balanced($content, $pos);
            $current .= substr($content, $pos, $end - $pos + 1);
            $pos = $end + 1;
        } elsif ($ch =~ /\s/) {
            if ($current ne '') {
                push @result, [$current, $preceding_ws];
                $current = '';
                $preceding_ws = '';
            }
            $preceding_ws .= $ch;
            $pos++;
        } elsif ($ch eq ':') {
            if ($current ne '' && $current =~ /^[a-zA-Z_][a-zA-Z0-9_]*$/) {
                $current .= ':';
                push @result, [$current, $preceding_ws];
                $current = '';
                $preceding_ws = '';
            } else {
                $current .= ':';
            }
            $pos++;
        } else {
            $current .= $ch;
            $pos++;
        }
    }
    push @result, [$current, $preceding_ws] if $current ne '';
    
    return @result;
}

sub parse_message_send {
    my ($content) = @_;
    
    return undef if has_top_level_comma($content);
    
    my @tokens = tokenize_message($content);
    
    return undef if @tokens == 0;
    
    my ($receiver, $recv_ws) = @{shift @tokens};
    
    return undef if @tokens == 0;
    
    # Unary message
    if (@tokens == 1 && $tokens[0][0] =~ /^[a-zA-Z_][a-zA-Z0-9_]*$/) {
        my ($sel, $sel_ws) = @{$tokens[0]};
        return [
            [$receiver, ''],
            ["'$sel'", $sel_ws]
        ];
    }
    
    return undef unless $tokens[0][0] =~ /^[a-zA-Z_][a-zA-Z0-9_]*:$/;
    
    my @parts = ([$receiver, '']);
    
    while (@tokens) {
        my ($tok, $ws) = @{shift @tokens};
        
        if ($tok =~ /^[a-zA-Z_][a-zA-Z0-9_]*:$/) {
            push @parts, ["'$tok'", $ws];
            if (@tokens) {
                my ($arg, $arg_ws) = @{shift @tokens};
                push @parts, [$arg, $arg_ws];
            }
        } else {
            if (@parts > 0) {
                $parts[-1][0] .= ' ' . $tok;
            }
        }
    }
    
    return \@parts;
}

sub format_send {
    my ($parts) = @_;
    
    # Check if any whitespace contains newline
    my $multiline = 0;
    for my $p (@$parts) {
        if ($p->[1] =~ /\n/) {
            $multiline = 1;
            last;
        }
    }
    
    if ($multiline) {
        # Preserve formatting
        my $out = 'send(';
        for my $i (0 .. $#$parts) {
            if ($i > 0) {
                $out .= ',';
                my $ws = $parts->[$i][1];
                if ($ws =~ /\n/) {
                    $out .= $ws;
                } else {
                    $out .= ' ';
                }
            }
            $out .= $parts->[$i][0];
        }
        $out .= ')';
        return $out;
    } else {
        # Single line
        return 'send(' . join(', ', map { $_->[0] } @$parts) . ')';
    }
}

sub transpile {
    my ($input) = @_;
    my $output = '';
    my $pos = 0;
    my $len = length($input);
    
    while ($pos < $len) {
        my $ch = substr($input, $pos, 1);
        
        if ($ch eq $OPEN) {
            my $end = find_matching_bracket($input, $pos + 1);
            if ($end == -1) {
                $output .= $ch;
                $pos++;
            } else {
                my $content = substr($input, $pos + 1, $end - $pos - 1);
                my $transpiled = transpile($content);
                my $parts = parse_message_send($transpiled);
                if (defined $parts) {
                    $output .= format_send($parts);
                } else {
                    $output .= $OPEN . $transpiled . $CLOSE;
                }
                $pos = $end + 1;
            }
        } else {
            $output .= $ch;
            $pos++;
        }
    }
    
    return $output;
}

my $input = do { local $/; <STDIN> };
print transpile($input);