// Generated by Claude Opus 4.5

const vscode = require('vscode');

function activate(context) {
    const disposable = vscode.workspace.onDidChangeTextDocument(event => {
        const editor = vscode.window.activeTextEditor;
        if (!editor || editor.document !== event.document) return;
        
        // Only for JS/TS files
        const lang = editor.document.languageId;
        if (!['javascript', 'typescript', 'javascriptreact', 'typescriptreact'].includes(lang)) return;
        
        for (const change of event.contentChanges) {
            // Case 1: Auto-bracket inserted '[]' after typing '[' when previous char was '['
            // Scenario: User types '[' -> get '[]' -> types '[' again -> get '[[]' + ']' from first auto
            // We need to detect '[[]' or '[[]]' and replace with just '⟦'
            if (change.text === '[]') {
                const pos = change.range.start;
                if (pos.character > 0) {
                    const charBefore = editor.document.getText(
                        new vscode.Range(pos.line, pos.character - 1, pos.line, pos.character)
                    );
                    if (charBefore === '[') {
                        // Check if there's a ']' after the inserted '[]' (from first auto-bracket)
                        const charAfter = editor.document.getText(
                            new vscode.Range(pos.line, pos.character + 2, pos.line, pos.character + 3)
                        );
                        const endCol = charAfter === ']' ? pos.character + 3 : pos.character + 2;
                        
                        const replaceRange = new vscode.Range(
                            pos.line, pos.character - 1,
                            pos.line, endCol
                        );
                        editor.edit(editBuilder => {
                            editBuilder.replace(replaceRange, '⟦');
                        }, { undoStopBefore: false, undoStopAfter: true });
                    }
                }
            }
            // Case 2: User typed '[' without auto-bracket (or auto-bracket disabled)
            else if (change.text === '[') {
                const pos = change.range.start;
                if (pos.character > 0) {
                    const charBefore = editor.document.getText(
                        new vscode.Range(pos.line, pos.character - 1, pos.line, pos.character)
                    );
                    if (charBefore === '[') {
                        // Replace '[[' with '⟦'
                        const replaceRange = new vscode.Range(
                            pos.line, pos.character - 1,
                            pos.line, pos.character + 1
                        );
                        editor.edit(editBuilder => {
                            editBuilder.replace(replaceRange, '⟦');
                        }, { undoStopBefore: false, undoStopAfter: true });
                    }
                }
            }
            // Case 3: User typed ']'
            else if (change.text === ']') {
                const pos = change.range.start;
                if (pos.character > 0) {
                    const charBefore = editor.document.getText(
                        new vscode.Range(pos.line, pos.character - 1, pos.line, pos.character)
                    );
                    if (charBefore === ']') {
                        // Replace ']]' with '⟧'
                        const replaceRange = new vscode.Range(
                            pos.line, pos.character - 1,
                            pos.line, pos.character + 1
                        );
                        editor.edit(editBuilder => {
                            editBuilder.replace(replaceRange, '⟧');
                        }, { undoStopBefore: false, undoStopAfter: true });
                    }
                }
            }
        }
    });

    context.subscriptions.push(disposable);
}

function deactivate() {}

module.exports = { activate, deactivate };
